export const avatarOptions = [
  {
    title: "ant",
    img: "bg-[url('/avatars/ant.svg')]",
    url: "/avatars/ant.svg",
    shadow: "bg-orange",
    dropShadow: "drop-shadow-orange",
    colorScheme: "a1",
  },
  {
    title: "app",
    img: "bg-[url('/avatars/app.svg')]",
    url: "/avatars/app.svg",
    shadow: "bg-lilac",
    dropShadow: "drop-shadow-lilac",
    colorScheme: "d5",
  },
  {
    title: "backpack",
    img: "bg-[url('/avatars/backpack.svg')]",
    url: "/avatars/backpack.svg",
    shadow: "bg-apricot",
    dropShadow: "drop-shadow-apricot",
    colorScheme: "f5",
  },
  {
    title: "bird",
    img: "bg-[url('/avatars/bird.svg')]",
    url: "/avatars/bird.svg",
    shadow: "bg-orange",
    dropShadow: "drop-shadow-orange",
    colorScheme: "a2",
  },
  {
    title: "books",
    img: "bg-[url('/avatars/books.svg')]",
    url: "/avatars/books.svg",
    shadow: "bg-sky",
    dropShadow: "drop-shadow-sky",
    colorScheme: "f1",
  },

  {
    title: "chess",
    img: "bg-[url('/avatars/chess.svg')]",
    url: "/avatars/chess.svg",
    shadow: "bg-watermelon",
    dropShadow: "drop-shadow-watermelon",
    colorScheme: "c1",
  },
  {
    title: "checks",
    img: "bg-[url('/avatars/checks.svg')]",
    url: "/avatars/checks.svg",
    shadow: "bg-magenta",
    dropShadow: "drop-shadow-magenta",
    colorScheme: "a5",
  },
  {
    title: "wave",
    img: "bg-[url('/avatars/wave.svg')]",
    url: "/avatars/wave.svg",
    shadow: "bg-lime",
    dropShadow: "drop-shadow-lime",
    colorScheme: "b1",
  },
  {
    title: "code",
    img: "bg-[url('/avatars/code.svg')]",
    url: "/avatars/code.svg",
    shadow: "bg-lilac",
    dropShadow: "drop-shadow-lilac",
    colorScheme: "d1",
  },
  {
    title: "mushrooms",
    img: "bg-[url('/avatars/mushrooms.svg')]",
    url: "./avatars/mushrooms.svg",
    shadow: "bg-lime",
    dropShadow: "drop-shadow-lime",
    colorScheme: "b6",
  },
  {
    title: "dice",
    img: "bg-[url('/avatars/dice.svg')]",
    url: "/avatars/dice.svg",
    shadow: "bg-lime",
    dropShadow: "drop-shadow-lime",
    colorScheme: "b4",
  },

  {
    title: "dino",
    img: "bg-[url('/avatars/dino.svg')]",
    url: "/avatars/dino.svg",
    shadow: "bg-sky",
    dropShadow: "drop-shadow-sky",
    colorScheme: "f1",
  },
  {
    title: "fish",
    img: "bg-[url('/avatars/fish.svg')]",
    url: "/avatars/fish.svg",
    shadow: "bg-peach",
    dropShadow: "drop-shadow-peach",
    colorScheme: "c6",
  },

  {
    title: "football",
    img: "bg-[url('/avatars/football.svg')]",
    url: "/avatars/football.svg",
    shadow: "bg-sky",
    dropShadow: "drop-shadow-sky",
    colorScheme: "f3",
  },
  {
    title: "flower",
    img: "bg-[url('/avatars/flower.svg')]",
    url: "/avatars/flower.svg",
    shadow: "bg-watermelon",
    dropShadow: "drop-shadow-watermelon",
    colorScheme: "c4",
  },
  {
    title: "medicine",
    img: "bg-[url('/avatars/medicine.svg')]",
    url: "/avatars/medicine.svg",
    shadow: "bg-olive",
    dropShadow: "drop-shadow-olive",
    colorScheme: "f5",
  },
  {
    title: "groovy",
    img: "bg-[url('/avatars/groovy.svg')]",
    url: "/avatars/groovy.svg",
    shadow: "bg-orange",
    dropShadow: "drop-shadow-orange",
    colorScheme: "a4",
  },

  {
    title: "ivy",
    img: "bg-[url('/avatars/ivy.svg')]",
    url: "/avatars/ivy.svg",
    shadow: "bg-jade",
    dropShadow: "drop-shadow-jade",
    colorScheme: "e5",
  },
  {
    title: "growth",
    img: "bg-[url('/avatars/growth.svg')]",
    url: "/avatars/growth.svg",
    shadow: "bg-lime",
    dropShadow: "drop-shadow-lime",
    colorScheme: "b5",
  },

  {
    title: "mug",
    img: "bg-[url('/avatars/mug.svg')]",
    url: "/avatars/mug.svg",
    shadow: "bg-lime",
    dropShadow: "drop-shadow-lime",
    colorScheme: "b3",
  },

  {
    title: "orange-floral",
    img: "bg-[url('/avatars/orange-floral.svg')]",
    url: "/avatars/orange-floral.svg",
    shadow: "bg-lime",
    dropShadow: "drop-shadow-lime",
    colorScheme: "b5",
  },
  {
    title: "music",
    img: "bg-[url('/avatars/music.svg')]",
    url: "/avatars/music.svg",
    shadow: "bg-jade",
    dropShadow: "drop-shadow-jade",
    colorScheme: "e6",
  },

  {
    title: "shades",
    img: "bg-[url('/avatars/shades.svg')]",
    url: "/avatars/shades.svg",
    shadow: "bg-magenta",
    dropShadow: "drop-shadow-magenta",
    colorScheme: "a6",
  },
  {
    title: "plant",
    img: "bg-[url('/avatars/plant.svg')]",
    url: "/avatars/plant.svg",
    shadow: "bg-lime",
    dropShadow: "drop-shadow-lime",
    colorScheme: "b6",
  },

  {
    title: "weights",
    img: "bg-[url('/avatars/weights.svg')]",
    url: "/avatars/weights.svg",
    shadow: "bg-apricot",
    dropShadow: "drop-shadow-apricot",
    colorScheme: "c6",
  },
];
