export const avatarOptions = [
  {
    title: "ant",
    img: "bg-[url('/avatars/ant.svg')]",
    shadow: "bg-jade",
    colorScheme: "e6",
  },
  {
    title: "app",
    img: "bg-[url('/avatars/app.svg')]",
    shadow: "bg-watermelon",
    colorScheme: "c4",
  },
  {
    title: "backpack",
    img: "bg-[url('/avatars/backpack.svg')]",
    shadow: "bg-lime",
    colorScheme: "b1",
  },
  {
    title: "bird",
    img: "bg-[url('/avatars/bird.svg')]",
    shadow: "bg-magenta",
    colorScheme: "a6",
  },
  {
    title: "books",
    img: "bg-[url('/avatars/books.svg')]",
    shadow: "bg-apricot",
    colorScheme: "e1",
  },
  {
    title: "cactus",
    img: "bg-[url('/avatars/cactus.svg')]",
    shadow: "bg-lime",
    colorScheme: "b4",
  },
  {
    title: "checks",
    img: "bg-[url('/avatars/checks.svg')]",
    shadow: "bg-lilac",
    colorScheme: "d1",
  },
  {
    title: "chess",
    img: "bg-[url('/avatars/chess.svg')]",
    shadow: "bg-lilac",
    colorScheme: "d3",
  },
  {
    title: "code",
    img: "bg-[url('/avatars/code.svg')]",
    shadow: "bg-apricot",
    colorScheme: "e4",
  },
  {
    title: "orange floral",
    img: "bg-[url('/avatars/orange-floral.svg')]",
    shadow: "bg-lime",
    colorScheme: "d4",
  },
  {
    title: "dice",
    img: "bg-[url('/avatars/dice.svg')]",
    shadow: "bg-sky",
    colorScheme: "f1",
  },
  {
    title: "dino",
    img: "bg-[url('/avatars/dino.svg')]",
    shadow: "bg-jade",
    colorScheme: "e5",
  },
  {
    title: "fish",
    img: "bg-[url('/avatars/fish.svg')]",
    shadow: "bg-watermelon",
    colorScheme: "c4",
  },
  {
    title: "flower",
    img: "bg-[url('/avatars/flower.svg')]",
    shadow: "bg-watermelon",
    colorScheme: "c4",
  },
  {
    title: "football",
    img: "bg-[url('/avatars/football.svg')]",
    shadow: "bg-watermelon",
    colorScheme: "c4",
  },
  {
    title: "groovy",
    img: "bg-[url('/avatars/groovy.svg')]",
    shadow: "bg-watermelon",
    colorScheme: "c4",
  },
  {
    title: "growth",
    img: "bg-[url('/avatars/growth.svg')]",
    shadow: "bg-watermelon",
    colorScheme: "c4",
  },
  {
    title: "flower",
    img: "bg-[url('/avatars/flower.svg')]",
    shadow: "bg-watermelon",
    colorScheme: "c4",
  },
  {
    title: "football",
    img: "bg-[url('/avatars/football.svg')]",
    shadow: "bg-watermelon",
    colorScheme: "c4",
  },
  {
    title: "groovy",
    img: "bg-[url('/avatars/groovy.svg')]",
    shadow: "bg-watermelon",
    colorScheme: "c4",
  },
  {
    title: "growth",
    img: "bg-[url('/avatars/growth.svg')]",
    shadow: "bg-watermelon",
    colorScheme: "c4",
  },
];
