export const buttonColors = {
  a1: {
    color1: "bg-watermelon",
    color2: "bg-orange",
    color3: "border-watermelon",
    color4: "border-orange",
    color5: "group-hover:bg-watermelon",
    color6: "group-hover:border-watermelon",
    color7: "group-hover:bg-orange",
    color8: "group-hover:border-orange",
  },
  a2: {
    color1: "bg-sky",
    color2: "bg-orange",
    color3: "border-sky",
    color4: "border-orange",
    color5: "group-hover:bg-sky",
    color6: "group-hover:border-sky",
    color7: "group-hover:bg-orange",
    color8: "group-hover:border-orange",
  },
  a3: {
    color1: "bg-magenta",
    color2: "bg-orange",
    color3: "border-magenta",
    color4: "border-orange",
    color5: "group-hover:bg-magenta",
    color6: "group-hover:border-magenta",
    color7: "group-hover:bg-orange",
    color8: "group-hover:border-orange",
  },
  a4: {
    color1: "bg-lilac",
    color2: "bg-orange",
    color3: "border-lilac",
    color4: "border-orange",
    color5: "group-hover:bg-lilac",
    color6: "group-hover:border-lilac",
    color7: "group-hover:bg-orange",
    color8: "group-hover:border-orange",
  },
  a5: {
    color1: "bg-orange",
    color2: "bg-magenta",
    color3: "border-orange",
    color4: "border-magenta",
    color5: "group-hover:bg-orange",
    color6: "group-hover:border-orange",
    color7: "group-hover:bg-magenta",
    color8: "group-hover:border-magenta",
  },
  a6: {
    color1: "bg-lime",
    color2: "bg-magenta",
    color3: "border-lime",
    color4: "border-magenta",
    color5: "group-hover:bg-lime",
    color6: "group-hover:border-lime",
    color7: "group-hover:bg-magenta",
    color8: "group-hover:border-magenta",
  },

  b1: {
    color1: "bg-jade",
    color2: "bg-lime",
    color3: "border-jade",
    color4: "border-lime",
    color5: "group-hover:bg-jade",
    color6: "group-hover:border-jade",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  b2: {
    color1: "bg-watermelon",
    color2: "bg-lime",
    color3: "border-watermelon",
    color4: "border-lime",
    color5: "group-hover:bg-watermelon",
    color6: "group-hover:border-watermelon",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  b3: {
    color1: "bg-lilac",
    color2: "bg-lime",
    color3: "border-lilac",
    color4: "border-lime",
    color5: "group-hover:bg-lilac",
    color6: "group-hover:border-lilac",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  b4: {
    color1: "bg-magenta",
    color2: "bg-lime",
    color3: "border-magenta",
    color4: "border-lime",
    color5: "group-hover:bg-magenta",
    color6: "group-hover:border-magenta",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  b5: {
    color1: "bg-orange",
    color2: "bg-lime",
    color3: "border-orange",
    color4: "border-lime",
    color5: "group-hover:bg-orange",
    color6: "group-hover:border-orange",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  b6: {
    color1: "bg-peach",
    color2: "bg-lime",
    color3: "border-peach",
    color4: "border-lime",
    color5: "group-hover:bg-peach",
    color6: "group-hover:border-peach",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },

  c1: {
    color1: "bg-olive",
    color2: "bg-watermelon",
    color3: "border-olive",
    color4: "border-watermelon",
    color5: "group-hover:bg-olive",
    color6: "group-hover:border-olive",
    color7: "group-hover:bg-watermelon",
    color8: "group-hover:border-watermelon",
  },
  c2: {
    color1: "bg-lime",
    color2: "bg-watermelon",
    color3: "border-lime",
    color4: "border-watermelon",
    color5: "group-hover:bg-lime",
    color6: "group-hover:border-lime",
    color7: "group-hover:bg-watermelon",
    color8: "group-hover:border-watermelon",
  },
  c3: {
    color1: "bg-orange",
    color2: "bg-watermelon",
    color3: "border-orange",
    color4: "border-watermelon",
    color5: "group-hover:bg-orange",
    color6: "group-hover:border-orange",
    color7: "group-hover:bg-watermelon",
    color8: "group-hover:border-watermelon",
  },
  c4: {
    color1: "bg-jade",
    color2: "bg-watermelon",
    color3: "border-jade",
    color4: "border-watermelon",
    color5: "group-hover:bg-jade",
    color6: "group-hover:border-jade",
    color7: "group-hover:bg-watermelon",
    color8: "group-hover:border-watermelon",
  },
  c5: {
    color1: "bg-emerald",
    color2: "bg-watermelon",
    color3: "border-emerald",
    color4: "border-watermelon",
    color5: "group-hover:bg-emerald",
    color6: "group-hover:border-emerald",
    color7: "group-hover:bg-watermelon",
    color8: "group-hover:border-watermelon",
  },
  c6: {
    color1: "bg-jade",
    color2: "bg-peach",
    color3: "border-jade",
    color4: "border-peach",
    color5: "group-hover:bg-jade",
    color6: "group-hover:border-jade",
    color7: "group-hover:bg-peach",
    color8: "group-hover:border-peach",
  },

  d1: {
    color1: "bg-emerald",
    color2: "bg-lilac",
    color3: "border-emerald",
    color4: "border-lilac",
    color5: "group-hover:bg-emerald",
    color6: "group-hover:border-emerald",
    color7: "group-hover:bg-lilac",
    color8: "group-hover:border-lilac",
  },
  d2: {
    color1: "bg-olive",
    color2: "bg-lilac",
    color3: "border-olive",
    color4: "border-lilac",
    color5: "group-hover:bg-olive",
    color6: "group-hover:border-olive",
    color7: "group-hover:bg-lilac",
    color8: "group-hover:border-lilac",
  },
  d3: {
    color1: "bg-jade",
    color2: "bg-lilac",
    color3: "border-jade",
    color4: "border-lilac",
    color5: "group-hover:bg-jade",
    color6: "group-hover:border-jade",
    color7: "group-hover:bg-lilac",
    color8: "group-hover:border-lilac",
  },
  d4: {
    color1: "bg-orange",
    color2: "bg-lilac",
    color3: "border-orange",
    color4: "border-lilac",
    color5: "group-hover:bg-orange",
    color6: "group-hover:border-orange",
    color7: "group-hover:bg-lilac",
    color8: "group-hover:border-lilac",
  },
  d5: {
    color1: "bg-lime",
    color2: "bg-lilac",
    color3: "border-lime",
    color4: "border-lilac",
    color5: "group-hover:bg-lime",
    color6: "group-hover:border-lime",
    color7: "group-hover:bg-lilac",
    color8: "group-hover:border-lilac",
  },
  d6: {
    color1: "bg-watermelon",
    color2: "bg-emerald",
    color3: "border-watermelon",
    color4: "border-emerald",
    color5: "group-hover:bg-watermelon",
    color6: "group-hover:border-watermelon",
    color7: "group-hover:bg-emerald",
    color8: "group-hover:border-emerald",
  },

  e1: {
    color1: "bg-magenta",
    color2: "bg-apricot",
    color3: "border-magenta",
    color4: "border-apricot",
    color5: "group-hover:bg-magenta",
    color6: "group-hover:border-magenta",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e2: {
    color1: "bg-lilac",
    color2: "bg-apricot",
    color3: "border-lilac",
    color4: "border-apricot",
    color5: "group-hover:bg-lilac",
    color6: "group-hover:border-lilac",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e3: {
    color1: "bg-sky",
    color2: "bg-apricot",
    color3: "border-sky",
    color4: "border-apricot",
    color5: "group-hover:bg-sky",
    color6: "group-hover:border-sky",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e4: {
    color1: "bg-olive",
    color2: "bg-apricot",
    color3: "border-olive",
    color4: "border-apricot",
    color5: "group-hover:bg-olive",
    color6: "group-hover:border-olive",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e5: {
    color1: "bg-watermelon",
    color2: "bg-jade",
    color3: "border-watermelon",
    color4: "border-jade",
    color5: "group-hover:bg-watermelon",
    color6: "group-hover:border-watermelon",
    color7: "group-hover:bg-jade",
    color8: "group-hover:border-jade",
  },
  e6: {
    color1: "bg-peach",
    color2: "bg-jade",
    color3: "border-peach",
    color4: "border-jade",
    color5: "group-hover:bg-peach",
    color6: "group-hover:border-peach",
    color7: "group-hover:bg-jade",
    color8: "group-hover:border-jade",
  },

  f1: {
    color1: "bg-orange",
    color2: "bg-sky",
    color3: "border-orange",
    color4: "border-sky",
    color5: "group-hover:bg-orange",
    color6: "group-hover:border-orange",
    color7: "group-hover:bg-sky",
    color8: "group-hover:border-sky",
  },
  f2: {
    color1: "bg-lime",
    color2: "bg-sky",
    color3: "border-lime",
    color4: "border-sky",
    color5: "group-hover:bg-lime",
    color6: "group-hover:border-lime",
    color7: "group-hover:bg-sky",
    color8: "group-hover:border-sky",
  },
  f3: {
    color1: "bg-olive",
    color2: "bg-sky",
    color3: "border-olive",
    color4: "border-sky",
    color5: "group-hover:bg-olive",
    color6: "group-hover:border-olive",
    color7: "group-hover:bg-sky",
    color8: "group-hover:border-sky",
  },
  f4: {
    color1: "bg-watermelon",
    color2: "bg-olive",
    color3: "border-watermelon",
    color4: "border-olive",
    color5: "group-hover:bg-watermelon",
    color6: "group-hover:border-watermelon",
    color7: "group-hover:bg-olive",
    color8: "group-hover:border-olive",
  },
  f5: {
    color1: "bg-peach",
    color2: "bg-olive",
    color3: "border-peach",
    color4: "border-olive",
    color5: "group-hover:bg-peach",
    color6: "group-hover:border-peach",
    color7: "group-hover:bg-olive",
    color8: "group-hover:border-olive",
  },
  f6: {
    color1: "bg-magenta",
    color2: "bg-peach",
    color3: "border-magenta",
    color4: "border-peach",
    color5: "group-hover:bg-magenta",
    color6: "group-hover:border-magenta",
    color7: "group-hover:bg-peach",
    color8: "group-hover:border-peach",
  },
};

export const highContrastButtonColors = {
  a1: {
    color1: "bg-cobalt",
    color2: "bg-lilac",
    color3: "border-cobalt",
    color4: "border-lilac",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-lilac",
    color8: "group-hover:border-lilac",
  },
  a2: {
    color1: "bg-azure",
    color2: "bg-violet",
    color3: "border-azure",
    color4: "border-violet",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-violet",
    color8: "group-hover:border-violet",
  },
  a3: {
    color1: "bg-violet",
    color2: "bg-pine",
    color3: "border-violet",
    color4: "border-pine",
    color5: "group-hover:bg-violet",
    color6: "group-hover:border-violet",
    color7: "group-hover:bg-pine",
    color8: "group-hover:border-pine",
  },
  a4: {
    color1: "bg-juniper",
    color2: "bg-azure",
    color3: "border-juniper",
    color4: "border-azure",
    color5: "group-hover:bg-juniper",
    color6: "group-hover:border-juniper",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  a5: {
    color1: "bg-pine",
    color2: "bg-denim",
    color3: "border-pine",
    color4: "border-denim",
    color5: "group-hover:bg-pine",
    color6: "group-hover:border-pine",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  a6: {
    color1: "bg-denim",
    color2: "bg-lime",
    color3: "border-denim",
    color4: "border-lime",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  b1: {
    color1: "bg-pine",
    color2: "bg-azure",
    color3: "border-pine",
    color4: "border-azure",
    color5: "group-hover:bg-pine",
    color6: "group-hover:border-pine",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  b2: {
    color1: "bg-cobalt",
    color2: "bg-lime",
    color3: "border-cobalt",
    color4: "border-lime",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  b3: {
    color1: "bg-juniper",
    color2: "bg-violet",
    color3: "border-juniper",
    color4: "border-violet",
    color5: "group-hover:bg-juniper",
    color6: "group-hover:border-juniper",
    color7: "group-hover:bg-violet",
    color8: "group-hover:border-violet",
  },
  b4: {
    color1: "bg-denim",
    color2: "bg-pine",
    color3: "border-denim",
    color4: "border-pine",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-pine",
    color8: "group-hover:border-pine",
  },
  b5: {
    color1: "bg-azure",
    color2: "bg-lime",
    color3: "border-azure",
    color4: "border-lime",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  b6: {
    color1: "bg-violet",
    color2: "bg-denim",
    color3: "border-violet",
    color4: "border-denim",
    color5: "group-hover:bg-violet",
    color6: "group-hover:border-violet",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  c1: {
    color1: "bg-azure",
    color2: "bg-cobalt",
    color3: "border-azure",
    color4: "border-cobalt",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  c2: {
    color1: "bg-lime",
    color2: "bg-juniper",
    color3: "border-lime",
    color4: "border-juniper",
    color5: "group-hover:bg-lime",
    color6: "group-hover:border-lime",
    color7: "group-hover:bg-juniper",
    color8: "group-hover:border-juniper",
  },
  c3: {
    color1: "bg-denim",
    color2: "bg-azure",
    color3: "border-denim",
    color4: "border-azure",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  c4: {
    color1: "bg-pine",
    color2: "bg-violet",
    color3: "border-pine",
    color4: "border-violet",
    color5: "group-hover:bg-pine",
    color6: "group-hover:border-pine",
    color7: "group-hover:bg-violet",
    color8: "group-hover:border-violet",
  },
  c5: {
    color1: "bg-juniper",
    color2: "bg-cobalt",
    color3: "border-juniper",
    color4: "border-cobalt",
    color5: "group-hover:bg-juniper",
    color6: "group-hover:border-juniper",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  c6: {
    color1: "bg-violet",
    color2: "bg-lime",
    color3: "border-violet",
    color4: "border-lime",
    color5: "group-hover:bg-violet",
    color6: "group-hover:border-violet",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  d1: {
    color1: "bg-cobalt",
    color2: "bg-pine",
    color3: "border-cobalt",
    color4: "border-pine",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-pine",
    color8: "group-hover:border-pine",
  },
  d2: {
    color1: "bg-azure",
    color2: "bg-denim",
    color3: "border-azure",
    color4: "border-denim",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  d3: {
    color1: "bg-juniper",
    color2: "bg-lime",
    color3: "border-juniper",
    color4: "border-lime",
    color5: "group-hover:bg-juniper",
    color6: "group-hover:border-juniper",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  d4: {
    color1: "bg-denim",
    color2: "bg-azure",
    color3: "border-denim",
    color4: "border-azure",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  d5: {
    color1: "bg-lime",
    color2: "bg-violet",
    color3: "border-lime",
    color4: "border-violet",
    color5: "group-hover:bg-lime",
    color6: "group-hover:border-lime",
    color7: "group-hover:bg-violet",
    color8: "group-hover:border-violet",
  },
  d6: {
    color1: "bg-pine",
    color2: "bg-cobalt",
    color3: "border-pine",
    color4: "border-cobalt",
    color5: "group-hover:bg-pine",
    color6: "group-hover:border-pine",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  e1: {
    color1: "bg-violet",
    color2: "bg-juniper",
    color3: "border-violet",
    color4: "border-juniper",
    color5: "group-hover:bg-violet",
    color6: "group-hover:border-violet",
    color7: "group-hover:bg-juniper",
    color8: "group-hover:border-juniper",
  },
  e2: {
    color1: "bg-denim",
    color2: "bg-azure",
    color3: "border-denim",
    color4: "border-azure",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  e3: {
    color1: "bg-cobalt",
    color2: "bg-lime",
    color3: "border-cobalt",
    color4: "border-lime",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  e4: {
    color1: "bg-azure",
    color2: "bg-pine",
    color3: "border-azure",
    color4: "border-pine",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-pine",
    color8: "group-hover:border-pine",
  },
  e5: {
    color1: "bg-juniper",
    color2: "bg-violet",
    color3: "border-juniper",
    color4: "border-violet",
    color5: "group-hover:bg-juniper",
    color6: "group-hover:border-juniper",
    color7: "group-hover:bg-violet",
    color8: "group-hover:border-violet",
  },
  e6: {
    color1: "bg-lime",
    color2: "bg-denim",
    color3: "border-lime",
    color4: "border-denim",
    color5: "group-hover:bg-lime",
    color6: "group-hover:border-lime",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  f1: {
    color1: "bg-denim",
    color2: "bg-cobalt",
    color3: "border-denim",
    color4: "border-cobalt",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  f2: {
    color1: "bg-lime",
    color2: "bg-azure",
    color3: "border-lime",
    color4: "border-azure",
    color5: "group-hover:bg-lime",
    color6: "group-hover:border-lime",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  f3: {
    color1: "bg-azure",
    color2: "bg-juniper",
    color3: "border-azure",
    color4: "border-juniper",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-juniper",
    color8: "group-hover:border-juniper",
  },
  f4: {
    color1: "bg-pine",
    color2: "bg-violet",
    color3: "border-pine",
    color4: "border-violet",
    color5: "group-hover:bg-pine",
    color6: "group-hover:border-pine",
    color7: "group-hover:bg-violet",
    color8: "group-hover:border-violet",
  },
  f5: {
    color1: "bg-violet",
    color2: "bg-lime",
    color3: "border-violet",
    color4: "border-lime",
    color5: "group-hover:bg-violet",
    color6: "group-hover:border-violet",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  f6: {
    color1: "bg-cobalt",
    color2: "bg-denim",
    color3: "border-cobalt",
    color4: "border-denim",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
};

export type ButtonColors = typeof buttonColors;
export type HighContrastButtonColors = typeof highContrastButtonColors;

// This defines the type of that array
export type ButtonColorOption = keyof typeof buttonColors;

// This is a dynamically generated array that includes the list of all of the keys from the ButtonColor object
export const buttonColorOptions = Object.keys(
  buttonColors,
) as ButtonColorOption[];
