export const buttonColors = {
  a1: {
    color1: "bg-berry",
    color2: "bg-pumpkin",
    color3: "border-berry",
    color4: "border-pumpkin",
    color5: "group-hover:bg-berry",
    color6: "group-hover:border-berry",
    color7: "group-hover:bg-pumpkin",
    color8: "group-hover:border-pumpkin",
  },
  a2: {
    color1: "bg-ice",
    color2: "bg-pumpkin",
    color3: "border-ice",
    color4: "border-pumpkin",
    color5: "group-hover:bg-ice",
    color6: "group-hover:border-ice",
    color7: "group-hover:bg-pumpkin",
    color8: "group-hover:border-pumpkin",
  },
  a3: {
    color1: "bg-wine",
    color2: "bg-pumpkin",
    color3: "border-wine",
    color4: "border-pumpkin",
    color5: "group-hover:bg-wine",
    color6: "group-hover:border-wine",
    color7: "group-hover:bg-pumpkin",
    color8: "group-hover:border-pumpkin",
  },
  a4: {
    color1: "bg-plum",
    color2: "bg-pumpkin",
    color3: "border-plum",
    color4: "border-pumpkin",
    color5: "group-hover:bg-plum",
    color6: "group-hover:border-plum",
    color7: "group-hover:bg-pumpkin",
    color8: "group-hover:border-pumpkin",
  },
  a5: {
    color1: "bg-pumpkin",
    color2: "bg-wine",
    color3: "border-pumpkin",
    color4: "border-wine",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-wine",
    color8: "group-hover:border-wine",
  },
  a6: {
    color1: "bg-moss",
    color2: "bg-wine",
    color3: "border-moss",
    color4: "border-wine",
    color5: "group-hover:bg-moss",
    color6: "group-hover:border-moss",
    color7: "group-hover:bg-wine",
    color8: "group-hover:border-wine",
  },

  b1: {
    color1: "bg-holly",
    color2: "bg-moss",
    color3: "border-holly",
    color4: "border-moss",
    color5: "group-hover:bg-holly",
    color6: "group-hover:border-holly",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
  b2: {
    color1: "bg-berry",
    color2: "bg-moss",
    color3: "border-berry",
    color4: "border-moss",
    color5: "group-hover:bg-berry",
    color6: "group-hover:border-berry",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
  b3: {
    color1: "bg-plum",
    color2: "bg-moss",
    color3: "border-plum",
    color4: "border-moss",
    color5: "group-hover:bg-plum",
    color6: "group-hover:border-plum",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
  b4: {
    color1: "bg-wine",
    color2: "bg-moss",
    color3: "border-wine",
    color4: "border-moss",
    color5: "group-hover:bg-wine",
    color6: "group-hover:border-wine",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
  b5: {
    color1: "bg-pumpkin",
    color2: "bg-moss",
    color3: "border-pumpkin",
    color4: "border-moss",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
  b6: {
    color1: "bg-apple",
    color2: "bg-moss",
    color3: "border-apple",
    color4: "border-moss",
    color5: "group-hover:bg-apple",
    color6: "group-hover:border-apple",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },

  c1: {
    color1: "bg-sage",
    color2: "bg-berry",
    color3: "border-sage",
    color4: "border-berry",
    color5: "group-hover:bg-sage",
    color6: "group-hover:border-sage",
    color7: "group-hover:bg-berry",
    color8: "group-hover:border-berry",
  },
  c2: {
    color1: "bg-moss",
    color2: "bg-berry",
    color3: "border-moss",
    color4: "border-berry",
    color5: "group-hover:bg-moss",
    color6: "group-hover:border-moss",
    color7: "group-hover:bg-berry",
    color8: "group-hover:border-berry",
  },
  c3: {
    color1: "bg-pumpkin",
    color2: "bg-berry",
    color3: "border-pumpkin",
    color4: "border-berry",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-berry",
    color8: "group-hover:border-berry",
  },
  c4: {
    color1: "bg-holly",
    color2: "bg-berry",
    color3: "border-holly",
    color4: "border-berry",
    color5: "group-hover:bg-holly",
    color6: "group-hover:border-holly",
    color7: "group-hover:bg-berry",
    color8: "group-hover:border-berry",
  },
  c5: {
    color1: "bg-forest",
    color2: "bg-berry",
    color3: "border-forest",
    color4: "border-berry",
    color5: "group-hover:bg-forest",
    color6: "group-hover:border-forest",
    color7: "group-hover:bg-berry",
    color8: "group-hover:border-berry",
  },
  c6: {
    color1: "bg-holly",
    color2: "bg-apple",
    color3: "border-holly",
    color4: "border-apple",
    color5: "group-hover:bg-holly",
    color6: "group-hover:border-holly",
    color7: "group-hover:bg-apple",
    color8: "group-hover:border-apple",
  },

  d1: {
    color1: "bg-forest",
    color2: "bg-plum",
    color3: "border-forest",
    color4: "border-plum",
    color5: "group-hover:bg-forest",
    color6: "group-hover:border-forest",
    color7: "group-hover:bg-plum",
    color8: "group-hover:border-plum",
  },
  d2: {
    color1: "bg-sage",
    color2: "bg-plum",
    color3: "border-sage",
    color4: "border-plum",
    color5: "group-hover:bg-sage",
    color6: "group-hover:border-sage",
    color7: "group-hover:bg-plum",
    color8: "group-hover:border-plum",
  },
  d3: {
    color1: "bg-holly",
    color2: "bg-plum",
    color3: "border-holly",
    color4: "border-plum",
    color5: "group-hover:bg-holly",
    color6: "group-hover:border-holly",
    color7: "group-hover:bg-plum",
    color8: "group-hover:border-plum",
  },
  d4: {
    color1: "bg-pumpkin",
    color2: "bg-plum",
    color3: "border-pumpkin",
    color4: "border-plum",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-plum",
    color8: "group-hover:border-plum",
  },
  d5: {
    color1: "bg-moss",
    color2: "bg-plum",
    color3: "border-moss",
    color4: "border-plum",
    color5: "group-hover:bg-moss",
    color6: "group-hover:border-moss",
    color7: "group-hover:bg-plum",
    color8: "group-hover:border-plum",
  },
  d6: {
    color1: "bg-berry",
    color2: "bg-forest",
    color3: "border-berry",
    color4: "border-forest",
    color5: "group-hover:bg-berry",
    color6: "group-hover:border-berry",
    color7: "group-hover:bg-forest",
    color8: "group-hover:border-forest",
  },

  e1: {
    color1: "bg-wine",
    color2: "bg-apricot",
    color3: "border-wine",
    color4: "border-apricot",
    color5: "group-hover:bg-wine",
    color6: "group-hover:border-wine",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e2: {
    color1: "bg-plum",
    color2: "bg-apricot",
    color3: "border-plum",
    color4: "border-apricot",
    color5: "group-hover:bg-plum",
    color6: "group-hover:border-plum",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e3: {
    color1: "bg-ice",
    color2: "bg-apricot",
    color3: "border-ice",
    color4: "border-apricot",
    color5: "group-hover:bg-ice",
    color6: "group-hover:border-ice",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e4: {
    color1: "bg-sage",
    color2: "bg-apricot",
    color3: "border-sage",
    color4: "border-apricot",
    color5: "group-hover:bg-sage",
    color6: "group-hover:border-sage",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e5: {
    color1: "bg-berry",
    color2: "bg-holly",
    color3: "border-berry",
    color4: "border-holly",
    color5: "group-hover:bg-berry",
    color6: "group-hover:border-berry",
    color7: "group-hover:bg-holly",
    color8: "group-hover:border-holly",
  },
  e6: {
    color1: "bg-apple",
    color2: "bg-holly",
    color3: "border-apple",
    color4: "border-holly",
    color5: "group-hover:bg-apple",
    color6: "group-hover:border-apple",
    color7: "group-hover:bg-holly",
    color8: "group-hover:border-holly",
  },

  f1: {
    color1: "bg-pumpkin",
    color2: "bg-ice",
    color3: "border-pumpkin",
    color4: "border-ice",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-ice",
    color8: "group-hover:border-ice",
  },
  f2: {
    color1: "bg-moss",
    color2: "bg-ice",
    color3: "border-moss",
    color4: "border-ice",
    color5: "group-hover:bg-moss",
    color6: "group-hover:border-moss",
    color7: "group-hover:bg-ice",
    color8: "group-hover:border-ice",
  },
  f3: {
    color1: "bg-sage",
    color2: "bg-ice",
    color3: "border-sage",
    color4: "border-ice",
    color5: "group-hover:bg-sage",
    color6: "group-hover:border-sage",
    color7: "group-hover:bg-ice",
    color8: "group-hover:border-ice",
  },
  f4: {
    color1: "bg-berry",
    color2: "bg-sage",
    color3: "border-berry",
    color4: "border-sage",
    color5: "group-hover:bg-berry",
    color6: "group-hover:border-berry",
    color7: "group-hover:bg-sage",
    color8: "group-hover:border-sage",
  },
  f5: {
    color1: "bg-apple",
    color2: "bg-sage",
    color3: "border-apple",
    color4: "border-sage",
    color5: "group-hover:bg-apple",
    color6: "group-hover:border-apple",
    color7: "group-hover:bg-sage",
    color8: "group-hover:border-sage",
  },
  f6: {
    color1: "bg-wine",
    color2: "bg-apple",
    color3: "border-wine",
    color4: "border-apple",
    color5: "group-hover:bg-wine",
    color6: "group-hover:border-wine",
    color7: "group-hover:bg-apple",
    color8: "group-hover:border-apple",
  },
};

export const highContrastButtonColors = {
  a1: {
    color1: "bg-azure",
    color2: "bg-lapis",
    color3: "border-azure",
    color4: "border-lapis",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-lapis",
    color8: "group-hover:border-lapis",
  },
  a2: {
    color1: "bg-denim",
    color2: "bg-azure",
    color3: "border-denim",
    color4: "border-azure",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  a3: {
    color1: "bg-lapis",
    color2: "bg-denim",
    color3: "border-lapis",
    color4: "border-denim",
    color5: "group-hover:bg-lapis",
    color6: "group-hover:border-lapis",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  a4: {
    color1: "bg-azure",
    color2: "bg-mist",
    color3: "border-azure",
    color4: "border-mist",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-mist",
    color8: "group-hover:border-mist",
  },
  a5: {
    color1: "bg-ocean",
    color2: "bg-denim",
    color3: "border-ocean",
    color4: "border-denim",
    color5: "group-hover:bg-ocean",
    color6: "group-hover:border-ocean",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  a6: {
    color1: "bg-lapis",
    color2: "bg-mist",
    color3: "border-lapis",
    color4: "border-mist",
    color5: "group-hover:bg-lapis",
    color6: "group-hover:border-lapis",
    color7: "group-hover:bg-mist",
    color8: "group-hover:border-mist",
  },
  b1: {
    color1: "bg-cobalt",
    color2: "bg-mist",
    color3: "border-cobalt",
    color4: "border-mist",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-mist",
    color8: "group-hover:border-mist",
  },
  b2: {
    color1: "bg-denim",
    color2: "bg-lapis",
    color3: "border-denim",
    color4: "border-lapis",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-lapis",
    color8: "group-hover:border-lapis",
  },
  b3: {
    color1: "bg-azure",
    color2: "bg-denim",
    color3: "border-azure",
    color4: "border-denim",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  b4: {
    color1: "bg-azure",
    color2: "bg-denim",
    color3: "border-azure",
    color4: "border-denim",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  b5: {
    color1: "bg-denim",
    color2: "bg-cobalt",
    color3: "border-denim",
    color4: "border-cobalt",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  b6: {
    color1: "bg-azure",
    color2: "bg-denim",
    color3: "border-azure",
    color4: "border-denim",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  c1: {
    color1: "bg-azure",
    color2: "bg-ocean",
    color3: "border-azure",
    color4: "border-ocean",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-ocean",
    color8: "group-hover:border-ocean",
  },
  c2: {
    color1: "bg-lapis",
    color2: "bg-cobalt",
    color3: "border-lapis",
    color4: "border-cobalt",
    color5: "group-hover:bg-lapis",
    color6: "group-hover:border-lapis",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  c3: {
    color1: "bg-denim",
    color2: "bg-ocean",
    color3: "border-denim",
    color4: "border-ocean",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-ocean",
    color8: "group-hover:border-ocean",
  },
  c4: {
    color1: "bg-ocean",
    color2: "bg-azure",
    color3: "border-ocean",
    color4: "border-azure",
    color5: "group-hover:bg-ocean",
    color6: "group-hover:border-ocean",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  c5: {
    color1: "bg-ocean",
    color2: "bg-cobalt",
    color3: "border-ocean",
    color4: "border-cobalt",
    color5: "group-hover:bg-ocean",
    color6: "group-hover:border-ocean",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  c6: {
    color1: "bg-cobalt",
    color2: "bg-ocean",
    color3: "border-cobalt",
    color4: "border-ocean",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-ocean",
    color8: "group-hover:border-ocean",
  },
  d1: {
    color1: "bg-azure",
    color2: "bg-lapis",
    color3: "border-azure",
    color4: "border-lapis",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-lapis",
    color8: "group-hover:border-lapis",
  },
  d2: {
    color1: "bg-denim",
    color2: "bg-azure",
    color3: "border-denim",
    color4: "border-azure",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  d3: {
    color1: "bg-lapis",
    color2: "bg-denim",
    color3: "border-lapis",
    color4: "border-denim",
    color5: "group-hover:bg-lapis",
    color6: "group-hover:border-lapis",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  d4: {
    color1: "bg-azure",
    color2: "bg-mist",
    color3: "border-azure",
    color4: "border-mist",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-mist",
    color8: "group-hover:border-mist",
  },
  d5: {
    color1: "bg-ocean",
    color2: "bg-denim",
    color3: "border-ocean",
    color4: "border-denim",
    color5: "group-hover:bg-ocean",
    color6: "group-hover:border-ocean",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  d6: {
    color1: "bg-lapis",
    color2: "bg-mist",
    color3: "border-lapis",
    color4: "border-mist",
    color5: "group-hover:bg-lapis",
    color6: "group-hover:border-lapis",
    color7: "group-hover:bg-mist",
    color8: "group-hover:border-mist",
  },
  e1: {
    color1: "bg-cobalt",
    color2: "bg-mist",
    color3: "border-cobalt",
    color4: "border-mist",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-mist",
    color8: "group-hover:border-mist",
  },
  e2: {
    color1: "bg-denim",
    color2: "bg-lapis",
    color3: "border-denim",
    color4: "border-lapis",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-lapis",
    color8: "group-hover:border-lapis",
  },
  e3: {
    color1: "bg-cobalt",
    color2: "bg-denim",
    color3: "border-cobalt",
    color4: "border-denim",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  e4: {
    color1: "bg-cobalt",
    color2: "bg-lapis",
    color3: "border-cobalt",
    color4: "border-lapis",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-lapis",
    color8: "group-hover:border-lapis",
  },
  e5: {
    color1: "bg-cobalt",
    color2: "bg-lapis",
    color3: "border-cobalt",
    color4: "border-lapis",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-lapis",
    color8: "group-hover:border-lapis",
  },
  e6: {
    color1: "bg-azure",
    color2: "bg-denim",
    color3: "border-azure",
    color4: "border-denim",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  f1: {
    color1: "bg-azure",
    color2: "bg-ocean",
    color3: "border-azure",
    color4: "border-ocean",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-ocean",
    color8: "group-hover:border-ocean",
  },
  f2: {
    color1: "bg-lapis",
    color2: "bg-cobalt",
    color3: "border-lapis",
    color4: "border-cobalt",
    color5: "group-hover:bg-lapis",
    color6: "group-hover:border-lapis",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  f3: {
    color1: "bg-denim",
    color2: "bg-ocean",
    color3: "border-denim",
    color4: "border-ocean",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-ocean",
    color8: "group-hover:border-ocean",
  },
  f4: {
    color1: "bg-ocean",
    color2: "bg-azure",
    color3: "border-ocean",
    color4: "border-azure",
    color5: "group-hover:bg-ocean",
    color6: "group-hover:border-ocean",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  f5: {
    color1: "bg-ocean",
    color2: "bg-cobalt",
    color3: "border-ocean",
    color4: "border-cobalt",
    color5: "group-hover:bg-ocean",
    color6: "group-hover:border-ocean",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  f6: {
    color1: "bg-cobalt",
    color2: "bg-ocean",
    color3: "border-cobalt",
    color4: "border-ocean",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-ocean",
    color8: "group-hover:border-ocean",
  },
};

export const seasonalButtonColors = {
  a1: {
    color1: "bg-berry",
    color2: "bg-pumpkin",
    color3: "border-berry",
    color4: "border-pumpkin",
    color5: "group-hover:bg-berry",
    color6: "group-hover:border-berry",
    color7: "group-hover:bg-pumpkin",
    color8: "group-hover:border-pumpkin",
  },
  a2: {
    color1: "bg-ice",
    color2: "bg-pumpkin",
    color3: "border-ice",
    color4: "border-pumpkin",
    color5: "group-hover:bg-ice",
    color6: "group-hover:border-ice",
    color7: "group-hover:bg-pumpkin",
    color8: "group-hover:border-pumpkin",
  },
  a3: {
    color1: "bg-wine",
    color2: "bg-pumpkin",
    color3: "border-wine",
    color4: "border-pumpkin",
    color5: "group-hover:bg-wine",
    color6: "group-hover:border-wine",
    color7: "group-hover:bg-pumpkin",
    color8: "group-hover:border-pumpkin",
  },
  a4: {
    color1: "bg-plum",
    color2: "bg-pumpkin",
    color3: "border-plum",
    color4: "border-pumpkin",
    color5: "group-hover:bg-plum",
    color6: "group-hover:border-plum",
    color7: "group-hover:bg-pumpkin",
    color8: "group-hover:border-pumpkin",
  },
  a5: {
    color1: "bg-pumpkin",
    color2: "bg-wine",
    color3: "border-pumpkin",
    color4: "border-wine",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-wine",
    color8: "group-hover:border-wine",
  },
  a6: {
    color1: "bg-moss",
    color2: "bg-wine",
    color3: "border-moss",
    color4: "border-wine",
    color5: "group-hover:bg-moss",
    color6: "group-hover:border-moss",
    color7: "group-hover:bg-wine",
    color8: "group-hover:border-wine",
  },

  b1: {
    color1: "bg-holly",
    color2: "bg-moss",
    color3: "border-holly",
    color4: "border-moss",
    color5: "group-hover:bg-holly",
    color6: "group-hover:border-holly",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
  b2: {
    color1: "bg-berry",
    color2: "bg-moss",
    color3: "border-berry",
    color4: "border-moss",
    color5: "group-hover:bg-berry",
    color6: "group-hover:border-berry",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
  b3: {
    color1: "bg-plum",
    color2: "bg-moss",
    color3: "border-plum",
    color4: "border-moss",
    color5: "group-hover:bg-plum",
    color6: "group-hover:border-plum",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
  b4: {
    color1: "bg-wine",
    color2: "bg-moss",
    color3: "border-wine",
    color4: "border-moss",
    color5: "group-hover:bg-wine",
    color6: "group-hover:border-wine",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
  b5: {
    color1: "bg-pumpkin",
    color2: "bg-moss",
    color3: "border-pumpkin",
    color4: "border-moss",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
  b6: {
    color1: "bg-apple",
    color2: "bg-moss",
    color3: "border-apple",
    color4: "border-moss",
    color5: "group-hover:bg-apple",
    color6: "group-hover:border-apple",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },

  c1: {
    color1: "bg-sage",
    color2: "bg-berry",
    color3: "border-sage",
    color4: "border-berry",
    color5: "group-hover:bg-sage",
    color6: "group-hover:border-sage",
    color7: "group-hover:bg-berry",
    color8: "group-hover:border-berry",
  },
  c2: {
    color1: "bg-moss",
    color2: "bg-berry",
    color3: "border-moss",
    color4: "border-berry",
    color5: "group-hover:bg-moss",
    color6: "group-hover:border-moss",
    color7: "group-hover:bg-berry",
    color8: "group-hover:border-berry",
  },
  c3: {
    color1: "bg-pumpkin",
    color2: "bg-berry",
    color3: "border-pumpkin",
    color4: "border-berry",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-berry",
    color8: "group-hover:border-berry",
  },
  c4: {
    color1: "bg-holly",
    color2: "bg-berry",
    color3: "border-holly",
    color4: "border-berry",
    color5: "group-hover:bg-holly",
    color6: "group-hover:border-holly",
    color7: "group-hover:bg-berry",
    color8: "group-hover:border-berry",
  },
  c5: {
    color1: "bg-forest",
    color2: "bg-berry",
    color3: "border-forest",
    color4: "border-berry",
    color5: "group-hover:bg-forest",
    color6: "group-hover:border-forest",
    color7: "group-hover:bg-berry",
    color8: "group-hover:border-berry",
  },
  c6: {
    color1: "bg-holly",
    color2: "bg-apple",
    color3: "border-holly",
    color4: "border-apple",
    color5: "group-hover:bg-holly",
    color6: "group-hover:border-holly",
    color7: "group-hover:bg-apple",
    color8: "group-hover:border-apple",
  },

  d1: {
    color1: "bg-forest",
    color2: "bg-plum",
    color3: "border-forest",
    color4: "border-plum",
    color5: "group-hover:bg-forest",
    color6: "group-hover:border-forest",
    color7: "group-hover:bg-plum",
    color8: "group-hover:border-plum",
  },
  d2: {
    color1: "bg-sage",
    color2: "bg-plum",
    color3: "border-sage",
    color4: "border-plum",
    color5: "group-hover:bg-sage",
    color6: "group-hover:border-sage",
    color7: "group-hover:bg-plum",
    color8: "group-hover:border-plum",
  },
  d3: {
    color1: "bg-holly",
    color2: "bg-plum",
    color3: "border-holly",
    color4: "border-plum",
    color5: "group-hover:bg-holly",
    color6: "group-hover:border-holly",
    color7: "group-hover:bg-plum",
    color8: "group-hover:border-plum",
  },
  d4: {
    color1: "bg-pumpkin",
    color2: "bg-plum",
    color3: "border-pumpkin",
    color4: "border-plum",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-plum",
    color8: "group-hover:border-plum",
  },
  d5: {
    color1: "bg-moss",
    color2: "bg-plum",
    color3: "border-moss",
    color4: "border-plum",
    color5: "group-hover:bg-moss",
    color6: "group-hover:border-moss",
    color7: "group-hover:bg-plum",
    color8: "group-hover:border-plum",
  },
  d6: {
    color1: "bg-berry",
    color2: "bg-forest",
    color3: "border-berry",
    color4: "border-forest",
    color5: "group-hover:bg-berry",
    color6: "group-hover:border-berry",
    color7: "group-hover:bg-forest",
    color8: "group-hover:border-forest",
  },

  e1: {
    color1: "bg-wine",
    color2: "bg-apricot",
    color3: "border-wine",
    color4: "border-apricot",
    color5: "group-hover:bg-wine",
    color6: "group-hover:border-wine",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e2: {
    color1: "bg-plum",
    color2: "bg-apricot",
    color3: "border-plum",
    color4: "border-apricot",
    color5: "group-hover:bg-plum",
    color6: "group-hover:border-plum",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e3: {
    color1: "bg-ice",
    color2: "bg-apricot",
    color3: "border-ice",
    color4: "border-apricot",
    color5: "group-hover:bg-ice",
    color6: "group-hover:border-ice",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e4: {
    color1: "bg-sage",
    color2: "bg-apricot",
    color3: "border-sage",
    color4: "border-apricot",
    color5: "group-hover:bg-sage",
    color6: "group-hover:border-sage",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e5: {
    color1: "bg-berry",
    color2: "bg-holly",
    color3: "border-berry",
    color4: "border-holly",
    color5: "group-hover:bg-berry",
    color6: "group-hover:border-berry",
    color7: "group-hover:bg-holly",
    color8: "group-hover:border-holly",
  },
  e6: {
    color1: "bg-apple",
    color2: "bg-holly",
    color3: "border-apple",
    color4: "border-holly",
    color5: "group-hover:bg-apple",
    color6: "group-hover:border-apple",
    color7: "group-hover:bg-holly",
    color8: "group-hover:border-holly",
  },

  f1: {
    color1: "bg-pumpkin",
    color2: "bg-ice",
    color3: "border-pumpkin",
    color4: "border-ice",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-ice",
    color8: "group-hover:border-ice",
  },
  f2: {
    color1: "bg-moss",
    color2: "bg-ice",
    color3: "border-moss",
    color4: "border-ice",
    color5: "group-hover:bg-moss",
    color6: "group-hover:border-moss",
    color7: "group-hover:bg-ice",
    color8: "group-hover:border-ice",
  },
  f3: {
    color1: "bg-sage",
    color2: "bg-ice",
    color3: "border-sage",
    color4: "border-ice",
    color5: "group-hover:bg-sage",
    color6: "group-hover:border-sage",
    color7: "group-hover:bg-ice",
    color8: "group-hover:border-ice",
  },
  f4: {
    color1: "bg-berry",
    color2: "bg-sage",
    color3: "border-berry",
    color4: "border-sage",
    color5: "group-hover:bg-berry",
    color6: "group-hover:border-berry",
    color7: "group-hover:bg-sage",
    color8: "group-hover:border-sage",
  },
  f5: {
    color1: "bg-apple",
    color2: "bg-sage",
    color3: "border-apple",
    color4: "border-sage",
    color5: "group-hover:bg-apple",
    color6: "group-hover:border-apple",
    color7: "group-hover:bg-sage",
    color8: "group-hover:border-sage",
  },
  f6: {
    color1: "bg-wine",
    color2: "bg-apple",
    color3: "border-wine",
    color4: "border-apple",
    color5: "group-hover:bg-wine",
    color6: "group-hover:border-wine",
    color7: "group-hover:bg-apple",
    color8: "group-hover:border-apple",
  },
};

export type ButtonColors = typeof buttonColors;
export type HighContrastButtonColors = typeof highContrastButtonColors;
export type SeasonalButtonColors = typeof seasonalButtonColors;

// This defines the type of that array
export type ButtonColorOption = keyof typeof buttonColors;

// This is a dynamically generated array that includes the list of all of the keys from the ButtonColor object
export const buttonColorOptions = Object.keys(
  buttonColors,
) as ButtonColorOption[];
