export const buttonColors = {
  a1: {
    color1: "bg-watermelon",
    color2: "bg-orange",
    color3: "border-watermelon",
    color4: "border-orange",
    color5: "group-hover:bg-watermelon",
    color6: "group-hover:border-watermelon",
    color7: "group-hover:bg-orange",
    color8: "group-hover:border-orange",
  },
  a2: {
    color1: "bg-sky",
    color2: "bg-orange",
    color3: "border-sky",
    color4: "border-orange",
    color5: "group-hover:bg-sky",
    color6: "group-hover:border-sky",
    color7: "group-hover:bg-orange",
    color8: "group-hover:border-orange",
  },
  a3: {
    color1: "bg-magenta",
    color2: "bg-orange",
    color3: "border-magenta",
    color4: "border-orange",
    color5: "group-hover:bg-magenta",
    color6: "group-hover:border-magenta",
    color7: "group-hover:bg-orange",
    color8: "group-hover:border-orange",
  },
  a4: {
    color1: "bg-lilac",
    color2: "bg-orange",
    color3: "border-lilac",
    color4: "border-orange",
    color5: "group-hover:bg-lilac",
    color6: "group-hover:border-lilac",
    color7: "group-hover:bg-orange",
    color8: "group-hover:border-orange",
  },
  a5: {
    color1: "bg-orange",
    color2: "bg-magenta",
    color3: "border-orange",
    color4: "border-magenta",
    color5: "group-hover:bg-orange",
    color6: "group-hover:border-orange",
    color7: "group-hover:bg-magenta",
    color8: "group-hover:border-magenta",
  },
  a6: {
    color1: "bg-lime",
    color2: "bg-magenta",
    color3: "border-lime",
    color4: "border-magenta",
    color5: "group-hover:bg-lime",
    color6: "group-hover:border-lime",
    color7: "group-hover:bg-magenta",
    color8: "group-hover:border-magenta",
  },

  b1: {
    color1: "bg-jade",
    color2: "bg-lime",
    color3: "border-jade",
    color4: "border-lime",
    color5: "group-hover:bg-jade",
    color6: "group-hover:border-jade",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  b2: {
    color1: "bg-watermelon",
    color2: "bg-lime",
    color3: "border-watermelon",
    color4: "border-lime",
    color5: "group-hover:bg-watermelon",
    color6: "group-hover:border-watermelon",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  b3: {
    color1: "bg-lilac",
    color2: "bg-lime",
    color3: "border-lilac",
    color4: "border-lime",
    color5: "group-hover:bg-lilac",
    color6: "group-hover:border-lilac",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  b4: {
    color1: "bg-magenta",
    color2: "bg-lime",
    color3: "border-magenta",
    color4: "border-lime",
    color5: "group-hover:bg-magenta",
    color6: "group-hover:border-magenta",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  b5: {
    color1: "bg-orange",
    color2: "bg-lime",
    color3: "border-orange",
    color4: "border-lime",
    color5: "group-hover:bg-orange",
    color6: "group-hover:border-orange",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },
  b6: {
    color1: "bg-peach",
    color2: "bg-lime",
    color3: "border-peach",
    color4: "border-lime",
    color5: "group-hover:bg-peach",
    color6: "group-hover:border-peach",
    color7: "group-hover:bg-lime",
    color8: "group-hover:border-lime",
  },

  c1: {
    color1: "bg-olive",
    color2: "bg-watermelon",
    color3: "border-olive",
    color4: "border-watermelon",
    color5: "group-hover:bg-olive",
    color6: "group-hover:border-olive",
    color7: "group-hover:bg-watermelon",
    color8: "group-hover:border-watermelon",
  },
  c2: {
    color1: "bg-lime",
    color2: "bg-watermelon",
    color3: "border-lime",
    color4: "border-watermelon",
    color5: "group-hover:bg-lime",
    color6: "group-hover:border-lime",
    color7: "group-hover:bg-watermelon",
    color8: "group-hover:border-watermelon",
  },
  c3: {
    color1: "bg-orange",
    color2: "bg-watermelon",
    color3: "border-orange",
    color4: "border-watermelon",
    color5: "group-hover:bg-orange",
    color6: "group-hover:border-orange",
    color7: "group-hover:bg-watermelon",
    color8: "group-hover:border-watermelon",
  },
  c4: {
    color1: "bg-jade",
    color2: "bg-watermelon",
    color3: "border-jade",
    color4: "border-watermelon",
    color5: "group-hover:bg-jade",
    color6: "group-hover:border-jade",
    color7: "group-hover:bg-watermelon",
    color8: "group-hover:border-watermelon",
  },
  c5: {
    color1: "bg-emerald",
    color2: "bg-watermelon",
    color3: "border-emerald",
    color4: "border-watermelon",
    color5: "group-hover:bg-emerald",
    color6: "group-hover:border-emerald",
    color7: "group-hover:bg-watermelon",
    color8: "group-hover:border-watermelon",
  },
  c6: {
    color1: "bg-jade",
    color2: "bg-peach",
    color3: "border-jade",
    color4: "border-peach",
    color5: "group-hover:bg-jade",
    color6: "group-hover:border-jade",
    color7: "group-hover:bg-peach",
    color8: "group-hover:border-peach",
  },

  d1: {
    color1: "bg-emerald",
    color2: "bg-lilac",
    color3: "border-emerald",
    color4: "border-lilac",
    color5: "group-hover:bg-emerald",
    color6: "group-hover:border-emerald",
    color7: "group-hover:bg-lilac",
    color8: "group-hover:border-lilac",
  },
  d2: {
    color1: "bg-olive",
    color2: "bg-lilac",
    color3: "border-olive",
    color4: "border-lilac",
    color5: "group-hover:bg-olive",
    color6: "group-hover:border-olive",
    color7: "group-hover:bg-lilac",
    color8: "group-hover:border-lilac",
  },
  d3: {
    color1: "bg-jade",
    color2: "bg-lilac",
    color3: "border-jade",
    color4: "border-lilac",
    color5: "group-hover:bg-jade",
    color6: "group-hover:border-jade",
    color7: "group-hover:bg-lilac",
    color8: "group-hover:border-lilac",
  },
  d4: {
    color1: "bg-orange",
    color2: "bg-lilac",
    color3: "border-orange",
    color4: "border-lilac",
    color5: "group-hover:bg-orange",
    color6: "group-hover:border-orange",
    color7: "group-hover:bg-lilac",
    color8: "group-hover:border-lilac",
  },
  d5: {
    color1: "bg-lime",
    color2: "bg-lilac",
    color3: "border-lime",
    color4: "border-lilac",
    color5: "group-hover:bg-lime",
    color6: "group-hover:border-lime",
    color7: "group-hover:bg-lilac",
    color8: "group-hover:border-lilac",
  },
  d6: {
    color1: "bg-watermelon",
    color2: "bg-emerald",
    color3: "border-watermelon",
    color4: "border-emerald",
    color5: "group-hover:bg-watermelon",
    color6: "group-hover:border-watermelon",
    color7: "group-hover:bg-emerald",
    color8: "group-hover:border-emerald",
  },

  e1: {
    color1: "bg-magenta",
    color2: "bg-apricot",
    color3: "border-magenta",
    color4: "border-apricot",
    color5: "group-hover:bg-magenta",
    color6: "group-hover:border-magenta",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e2: {
    color1: "bg-lilac",
    color2: "bg-apricot",
    color3: "border-lilac",
    color4: "border-apricot",
    color5: "group-hover:bg-lilac",
    color6: "group-hover:border-lilac",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e3: {
    color1: "bg-sky",
    color2: "bg-apricot",
    color3: "border-sky",
    color4: "border-apricot",
    color5: "group-hover:bg-sky",
    color6: "group-hover:border-sky",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e4: {
    color1: "bg-olive",
    color2: "bg-apricot",
    color3: "border-olive",
    color4: "border-apricot",
    color5: "group-hover:bg-olive",
    color6: "group-hover:border-olive",
    color7: "group-hover:bg-apricot",
    color8: "group-hover:border-apricot",
  },
  e5: {
    color1: "bg-watermelon",
    color2: "bg-jade",
    color3: "border-watermelon",
    color4: "border-jade",
    color5: "group-hover:bg-watermelon",
    color6: "group-hover:border-watermelon",
    color7: "group-hover:bg-jade",
    color8: "group-hover:border-jade",
  },
  e6: {
    color1: "bg-peach",
    color2: "bg-jade",
    color3: "border-peach",
    color4: "border-jade",
    color5: "group-hover:bg-peach",
    color6: "group-hover:border-peach",
    color7: "group-hover:bg-jade",
    color8: "group-hover:border-jade",
  },

  f1: {
    color1: "bg-orange",
    color2: "bg-sky",
    color3: "border-orange",
    color4: "border-sky",
    color5: "group-hover:bg-orange",
    color6: "group-hover:border-orange",
    color7: "group-hover:bg-sky",
    color8: "group-hover:border-sky",
  },
  f2: {
    color1: "bg-lime",
    color2: "bg-sky",
    color3: "border-lime",
    color4: "border-sky",
    color5: "group-hover:bg-lime",
    color6: "group-hover:border-lime",
    color7: "group-hover:bg-sky",
    color8: "group-hover:border-sky",
  },
  f3: {
    color1: "bg-olive",
    color2: "bg-sky",
    color3: "border-olive",
    color4: "border-sky",
    color5: "group-hover:bg-olive",
    color6: "group-hover:border-olive",
    color7: "group-hover:bg-sky",
    color8: "group-hover:border-sky",
  },
  f4: {
    color1: "bg-watermelon",
    color2: "bg-olive",
    color3: "border-watermelon",
    color4: "border-olive",
    color5: "group-hover:bg-watermelon",
    color6: "group-hover:border-watermelon",
    color7: "group-hover:bg-olive",
    color8: "group-hover:border-olive",
  },
  f5: {
    color1: "bg-peach",
    color2: "bg-olive",
    color3: "border-peach",
    color4: "border-olive",
    color5: "group-hover:bg-peach",
    color6: "group-hover:border-peach",
    color7: "group-hover:bg-olive",
    color8: "group-hover:border-olive",
  },
  f6: {
    color1: "bg-magenta",
    color2: "bg-peach",
    color3: "border-magenta",
    color4: "border-peach",
    color5: "group-hover:bg-magenta",
    color6: "group-hover:border-magenta",
    color7: "group-hover:bg-peach",
    color8: "group-hover:border-peach",
  },
};

export const highContrastButtonColors = {
  a1: {
    color1: "bg-azure",
    color2: "bg-lapis",
    color3: "border-azure",
    color4: "border-lapis",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-lapis",
    color8: "group-hover:border-lapis",
  },
  a2: {
    color1: "bg-denim",
    color2: "bg-azure",
    color3: "border-denim",
    color4: "border-azure",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  a3: {
    color1: "bg-lapis",
    color2: "bg-denim",
    color3: "border-lapis",
    color4: "border-denim",
    color5: "group-hover:bg-lapis",
    color6: "group-hover:border-lapis",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  a4: {
    color1: "bg-azure",
    color2: "bg-mist",
    color3: "border-azure",
    color4: "border-mist",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-mist",
    color8: "group-hover:border-mist",
  },
  a5: {
    color1: "bg-ocean",
    color2: "bg-denim",
    color3: "border-ocean",
    color4: "border-denim",
    color5: "group-hover:bg-ocean",
    color6: "group-hover:border-ocean",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  a6: {
    color1: "bg-lapis",
    color2: "bg-mist",
    color3: "border-lapis",
    color4: "border-mist",
    color5: "group-hover:bg-lapis",
    color6: "group-hover:border-lapis",
    color7: "group-hover:bg-mist",
    color8: "group-hover:border-mist",
  },
  b1: {
    color1: "bg-cobalt",
    color2: "bg-mist",
    color3: "border-cobalt",
    color4: "border-mist",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-mist",
    color8: "group-hover:border-mist",
  },
  b2: {
    color1: "bg-denim",
    color2: "bg-lapis",
    color3: "border-denim",
    color4: "border-lapis",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-lapis",
    color8: "group-hover:border-lapis",
  },
  b3: {
    color1: "bg-azure",
    color2: "bg-denim",
    color3: "border-azure",
    color4: "border-denim",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  b4: {
    color1: "bg-azure",
    color2: "bg-denim",
    color3: "border-azure",
    color4: "border-denim",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  b5: {
    color1: "bg-denim",
    color2: "bg-cobalt",
    color3: "border-denim",
    color4: "border-cobalt",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  b6: {
    color1: "bg-azure",
    color2: "bg-denim",
    color3: "border-azure",
    color4: "border-denim",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  c1: {
    color1: "bg-azure",
    color2: "bg-ocean",
    color3: "border-azure",
    color4: "border-ocean",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-ocean",
    color8: "group-hover:border-ocean",
  },
  c2: {
    color1: "bg-lapis",
    color2: "bg-cobalt",
    color3: "border-lapis",
    color4: "border-cobalt",
    color5: "group-hover:bg-lapis",
    color6: "group-hover:border-lapis",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  c3: {
    color1: "bg-denim",
    color2: "bg-ocean",
    color3: "border-denim",
    color4: "border-ocean",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-ocean",
    color8: "group-hover:border-ocean",
  },
  c4: {
    color1: "bg-ocean",
    color2: "bg-azure",
    color3: "border-ocean",
    color4: "border-azure",
    color5: "group-hover:bg-ocean",
    color6: "group-hover:border-ocean",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  c5: {
    color1: "bg-ocean",
    color2: "bg-cobalt",
    color3: "border-ocean",
    color4: "border-cobalt",
    color5: "group-hover:bg-ocean",
    color6: "group-hover:border-ocean",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  c6: {
    color1: "bg-cobalt",
    color2: "bg-ocean",
    color3: "border-cobalt",
    color4: "border-ocean",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-ocean",
    color8: "group-hover:border-ocean",
  },
  d1: {
    color1: "bg-azure",
    color2: "bg-lapis",
    color3: "border-azure",
    color4: "border-lapis",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-lapis",
    color8: "group-hover:border-lapis",
  },
  d2: {
    color1: "bg-denim",
    color2: "bg-azure",
    color3: "border-denim",
    color4: "border-azure",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  d3: {
    color1: "bg-lapis",
    color2: "bg-denim",
    color3: "border-lapis",
    color4: "border-denim",
    color5: "group-hover:bg-lapis",
    color6: "group-hover:border-lapis",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  d4: {
    color1: "bg-azure",
    color2: "bg-mist",
    color3: "border-azure",
    color4: "border-mist",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-mist",
    color8: "group-hover:border-mist",
  },
  d5: {
    color1: "bg-ocean",
    color2: "bg-denim",
    color3: "border-ocean",
    color4: "border-denim",
    color5: "group-hover:bg-ocean",
    color6: "group-hover:border-ocean",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  d6: {
    color1: "bg-lapis",
    color2: "bg-mist",
    color3: "border-lapis",
    color4: "border-mist",
    color5: "group-hover:bg-lapis",
    color6: "group-hover:border-lapis",
    color7: "group-hover:bg-mist",
    color8: "group-hover:border-mist",
  },
  e1: {
    color1: "bg-cobalt",
    color2: "bg-mist",
    color3: "border-cobalt",
    color4: "border-mist",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-mist",
    color8: "group-hover:border-mist",
  },
  e2: {
    color1: "bg-denim",
    color2: "bg-lapis",
    color3: "border-denim",
    color4: "border-lapis",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-lapis",
    color8: "group-hover:border-lapis",
  },
  e3: {
    color1: "bg-cobalt",
    color2: "bg-denim",
    color3: "border-cobalt",
    color4: "border-denim",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  e4: {
    color1: "bg-cobalt",
    color2: "bg-lapis",
    color3: "border-cobalt",
    color4: "border-lapis",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-lapis",
    color8: "group-hover:border-lapis",
  },
  e5: {
    color1: "bg-cobalt",
    color2: "bg-lapis",
    color3: "border-cobalt",
    color4: "border-lapis",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-lapis",
    color8: "group-hover:border-lapis",
  },
  e6: {
    color1: "bg-azure",
    color2: "bg-denim",
    color3: "border-azure",
    color4: "border-denim",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-denim",
    color8: "group-hover:border-denim",
  },
  f1: {
    color1: "bg-azure",
    color2: "bg-ocean",
    color3: "border-azure",
    color4: "border-ocean",
    color5: "group-hover:bg-azure",
    color6: "group-hover:border-azure",
    color7: "group-hover:bg-ocean",
    color8: "group-hover:border-ocean",
  },
  f2: {
    color1: "bg-lapis",
    color2: "bg-cobalt",
    color3: "border-lapis",
    color4: "border-cobalt",
    color5: "group-hover:bg-lapis",
    color6: "group-hover:border-lapis",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  f3: {
    color1: "bg-denim",
    color2: "bg-ocean",
    color3: "border-denim",
    color4: "border-ocean",
    color5: "group-hover:bg-denim",
    color6: "group-hover:border-denim",
    color7: "group-hover:bg-ocean",
    color8: "group-hover:border-ocean",
  },
  f4: {
    color1: "bg-ocean",
    color2: "bg-azure",
    color3: "border-ocean",
    color4: "border-azure",
    color5: "group-hover:bg-ocean",
    color6: "group-hover:border-ocean",
    color7: "group-hover:bg-azure",
    color8: "group-hover:border-azure",
  },
  f5: {
    color1: "bg-ocean",
    color2: "bg-cobalt",
    color3: "border-ocean",
    color4: "border-cobalt",
    color5: "group-hover:bg-ocean",
    color6: "group-hover:border-ocean",
    color7: "group-hover:bg-cobalt",
    color8: "group-hover:border-cobalt",
  },
  f6: {
    color1: "bg-cobalt",
    color2: "bg-ocean",
    color3: "border-cobalt",
    color4: "border-ocean",
    color5: "group-hover:bg-cobalt",
    color6: "group-hover:border-cobalt",
    color7: "group-hover:bg-ocean",
    color8: "group-hover:border-ocean",
  },
};

export const seasonalButtonColors = {
  a1: {
    color1: "bg-orchid",
    color2: "bg-pumpkin",
    color3: "border-orchid",
    color4: "border-pumpkin",
    color5: "group-hover:bg-orchid",
    color6: "group-hover:border-orchid",
    color7: "group-hover:bg-pumpkin",
    color8: "group-hover:border-pumpkin",
  },
  a2: {
    color1: "bg-forest",
    color2: "bg-pumpkin",
    color3: "border-forest",
    color4: "border-pumpkin",
    color5: "group-hover:bg-forest",
    color6: "group-hover:border-forest",
    color7: "group-hover:bg-pumpkin",
    color8: "group-hover:border-pumpkin",
  },
  a3: {
    color1: "bg-spice",
    color2: "bg-pumpkin",
    color3: "border-spice",
    color4: "border-pumpkin",
    color5: "group-hover:bg-spice",
    color6: "group-hover:border-spice",
    color7: "group-hover:bg-pumpkin",
    color8: "group-hover:border-pumpkin",
  },
  a4: {
    color1: "bg-indigo",
    color2: "bg-pumpkin",
    color3: "border-indigo",
    color4: "border-pumpkin",
    color5: "group-hover:bg-indigo",
    color6: "group-hover:border-indigo",
    color7: "group-hover:bg-pumpkin",
    color8: "group-hover:border-pumpkin",
  },
  a5: {
    color1: "bg-pumpkin",
    color2: "bg-wine",
    color3: "border-pumpkin",
    color4: "border-wine",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-wine",
    color8: "group-hover:border-wine",
  },
  a6: {
    color1: "bg-honey",
    color2: "bg-pumpkin",
    color3: "border-honey",
    color4: "border-pumpkin",
    color5: "group-hover:bg-honey",
    color6: "group-hover:border-honey",
    color7: "group-hover:bg-pumpkin",
    color8: "group-hover:border-pumpkin",
  },
  b1: {
    color1: "bg-pine",
    color2: "bg-honey",
    color3: "border-pine",
    color4: "border-honey",
    color5: "group-hover:bg-pine",
    color6: "group-hover:border-pine",
    color7: "group-hover:bg-honey",
    color8: "group-hover:border-honey",
  },
  b2: {
    color1: "bg-berry",
    color2: "bg-honey",
    color3: "border-berry",
    color4: "border-honey",
    color5: "group-hover:bg-berry",
    color6: "group-hover:border-berry",
    color7: "group-hover:bg-honey",
    color8: "group-hover:border-honey",
  },
  b3: {
    color1: "bg-indigo",
    color2: "bg-honey",
    color3: "border-indigo",
    color4: "border-honey",
    color5: "group-hover:bg-indigo",
    color6: "group-hover:border-indigo",
    color7: "group-hover:bg-honey",
    color8: "group-hover:border-honey",
  },
  b4: {
    color1: "bg-spice",
    color2: "bg-honey",
    color3: "border-spice",
    color4: "border-honey",
    color5: "group-hover:bg-spice",
    color6: "group-hover:border-spice",
    color7: "group-hover:bg-honey",
    color8: "group-hover:border-honey",
  },
  b5: {
    color1: "bg-pumpkin",
    color2: "bg-honey",
    color3: "border-pumpkin",
    color4: "border-honey",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-honey",
    color8: "group-hover:border-honey",
  },
  b6: {
    color1: "bg-forest",
    color2: "bg-honey",
    color3: "border-forest",
    color4: "border-honey",
    color5: "group-hover:bg-forest",
    color6: "group-hover:border-forest",
    color7: "group-hover:bg-honey",
    color8: "group-hover:border-honey",
  },
  c1: {
    color1: "bg-wine",
    color2: "bg-orchid",
    color3: "border-wine",
    color4: "border-orchid",
    color5: "group-hover:bg-wine",
    color6: "group-hover:border-wine",
    color7: "group-hover:bg-orchid",
    color8: "group-hover:border-orchid",
  },
  c2: {
    color1: "bg-honey",
    color2: "bg-orchid",
    color3: "border-honey",
    color4: "border-orchid",
    color5: "group-hover:bg-honey",
    color6: "group-hover:border-honey",
    color7: "group-hover:bg-orchid",
    color8: "group-hover:border-orchid",
  },
  c3: {
    color1: "bg-pumpkin",
    color2: "bg-orchid",
    color3: "border-pumpkin",
    color4: "border-orchid",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-orchid",
    color8: "group-hover:border-orchid",
  },
  c4: {
    color1: "bg-pine",
    color2: "bg-orchid",
    color3: "border-pine",
    color4: "border-orchid",
    color5: "group-hover:bg-pine",
    color6: "group-hover:border-pine",
    color7: "group-hover:bg-orchid",
    color8: "group-hover:border-orchid",
  },
  c5: {
    color1: "bg-sage",
    color2: "bg-orchid",
    color3: "border-sage",
    color4: "border-orchid",
    color5: "group-hover:bg-sage",
    color6: "group-hover:border-sage",
    color7: "group-hover:bg-orchid",
    color8: "group-hover:border-orchid",
  },
  c6: {
    color1: "bg-pine",
    color2: "bg-moss",
    color3: "border-pine",
    color4: "border-moss",
    color5: "group-hover:bg-pine",
    color6: "group-hover:border-pine",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
  d1: {
    color1: "bg-sage",
    color2: "bg-indigo",
    color3: "border-sage",
    color4: "border-indigo",
    color5: "group-hover:bg-sage",
    color6: "group-hover:border-sage",
    color7: "group-hover:bg-indigo",
    color8: "group-hover:border-indigo",
  },
  d2: {
    color1: "bg-wine",
    color2: "bg-indigo",
    color3: "border-wine",
    color4: "border-indigo",
    color5: "group-hover:bg-wine",
    color6: "group-hover:border-wine",
    color7: "group-hover:bg-indigo",
    color8: "group-hover:border-indigo",
  },
  d3: {
    color1: "bg-pine",
    color2: "bg-indigo",
    color3: "border-pine",
    color4: "border-indigo",
    color5: "group-hover:bg-pine",
    color6: "group-hover:border-pine",
    color7: "group-hover:bg-indigo",
    color8: "group-hover:border-indigo",
  },
  d4: {
    color1: "bg-pumpkin",
    color2: "bg-indigo",
    color3: "border-pumpkin",
    color4: "border-indigo",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-indigo",
    color8: "group-hover:border-indigo",
  },
  d5: {
    color1: "bg-honey",
    color2: "bg-indigo",
    color3: "border-honey",
    color4: "border-indigo",
    color5: "group-hover:bg-honey",
    color6: "group-hover:border-honey",
    color7: "group-hover:bg-indigo",
    color8: "group-hover:border-indigo",
  },
  d6: {
    color1: "bg-orchid",
    color2: "bg-sage",
    color3: "border-orchid",
    color4: "border-sage",
    color5: "group-hover:bg-orchid",
    color6: "group-hover:border-orchid",
    color7: "group-hover:bg-sage",
    color8: "group-hover:border-sage",
  },
  e1: {
    color1: "bg-spice",
    color2: "bg-holly",
    color3: "border-spice",
    color4: "border-holly",
    color5: "group-hover:bg-spice",
    color6: "group-hover:border-spice",
    color7: "group-hover:bg-holly",
    color8: "group-hover:border-holly",
  },
  e2: {
    color1: "bg-indigo",
    color2: "bg-holly",
    color3: "border-indigo",
    color4: "border-holly",
    color5: "group-hover:bg-indigo",
    color6: "group-hover:border-indigo",
    color7: "group-hover:bg-holly",
    color8: "group-hover:border-holly",
  },
  e3: {
    color1: "bg-forest",
    color2: "bg-holly",
    color3: "border-forest",
    color4: "border-holly",
    color5: "group-hover:bg-forest",
    color6: "group-hover:border-forest",
    color7: "group-hover:bg-holly",
    color8: "group-hover:border-holly",
  },
  e4: {
    color1: "bg-wine",
    color2: "bg-holly",
    color3: "border-wine",
    color4: "border-holly",
    color5: "group-hover:bg-wine",
    color6: "group-hover:border-wine",
    color7: "group-hover:bg-holly",
    color8: "group-hover:border-holly",
  },
  e5: {
    color1: "bg-berry",
    color2: "bg-holly",
    color3: "border-berry",
    color4: "border-holly",
    color5: "group-hover:bg-berry",
    color6: "group-hover:border-berry",
    color7: "group-hover:bg-holly",
    color8: "group-hover:border-holly",
  },
  e6: {
    color1: "bg-forest",
    color2: "bg-holly",
    color3: "border-forest",
    color4: "border-holly",
    color5: "group-hover:bg-forest",
    color6: "group-hover:border-forest",
    color7: "group-hover:bg-holly",
    color8: "group-hover:border-holly",
  },
  f1: {
    color1: "bg-pumpkin",
    color2: "bg-ice",
    color3: "border-pumpkin",
    color4: "border-ice",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-ice",
    color8: "group-hover:border-ice",
  },
  f2: {
    color1: "bg-honey",
    color2: "bg-ice",
    color3: "border-honey",
    color4: "border-ice",
    color5: "group-hover:bg-honey",
    color6: "group-hover:border-honey",
    color7: "group-hover:bg-ice",
    color8: "group-hover:border-ice",
  },
  f3: {
    color1: "bg-wine",
    color2: "bg-ice",
    color3: "border-wine",
    color4: "border-ice",
    color5: "group-hover:bg-wine",
    color6: "group-hover:border-wine",
    color7: "group-hover:bg-ice",
    color8: "group-hover:border-ice",
  },
  f4: {
    color1: "bg-berry",
    color2: "bg-moss",
    color3: "border-berry",
    color4: "border-moss",
    color5: "group-hover:bg-berry",
    color6: "group-hover:border-berry",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
  f5: {
    color1: "bg-forest",
    color2: "bg-moss",
    color3: "border-forest",
    color4: "border-moss",
    color5: "group-hover:bg-forest",
    color6: "group-hover:border-forest",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
  f6: {
    color1: "bg-pumpkin",
    color2: "bg-moss",
    color3: "border-pumpkin",
    color4: "border-moss",
    color5: "group-hover:bg-pumpkin",
    color6: "group-hover:border-pumpkin",
    color7: "group-hover:bg-moss",
    color8: "group-hover:border-moss",
  },
};

export type ButtonColors = typeof buttonColors;
export type HighContrastButtonColors = typeof highContrastButtonColors;
export type SeasonalButtonColors = typeof seasonalButtonColors;

// This defines the type of that array
export type ButtonColorOption = keyof typeof buttonColors;

// This is a dynamically generated array that includes the list of all of the keys from the ButtonColor object
export const buttonColorOptions = Object.keys(
  buttonColors,
) as ButtonColorOption[];
