type ButtonColors = {
  [key: string]: {
    color1: string;
    color2: string;
  };
};

export const buttonColors: ButtonColors = {
  a1: { color1: "bg-orange", color2: "bg-lime" },
  a2: { color1: "bg-magenta", color2: "bg-jade" },
  a3: { color1: "bg-lime", color2: "bg-orange" },
  a4: { color1: "bg-jade", color2: "bg-apricot" },
  a5: { color1: "bg-sky", color2: "bg-watermelon" },
  a6: { color1: "bg-watermelon", color2: "bg-emerald" },
  a7: { color1: "bg-orange", color2: "bg-lime" },
  a8: { color1: "bg-lilac", color2: "bg-apricot" },
  a9: { color1: "bg-emerald", color2: "bg-apricot" },
  a10: { color1: "bg-lime", color2: "bg-lilac" },
  b1: { color1: "bg-apricot", color2: "bg-jade" },
  b2: { color1: "bg-watermelon", color2: "bg-lilac" },
  b3: { color1: "bg-orange", color2: "bg-emerald" },
  b4: { color1: "bg-apricot", color2: "bg-sky" },
  b5: { color1: "bg-watermelon", color2: "bg-olive" },
  b6: { color1: "bg-midnight", color2: "bg-sky" },
  b7: { color1: "bg-lime", color2: "bg-midnight" },
  b8: { color1: "bg-apricot", color2: "bg-watermelon" },
  b9: { color1: "bg-apricot", color2: "bg-lilac" },
  b10: { color1: "bg-lilac", color2: "bg-watermelon" },
  c1: { color1: "bg-emerald", color2: "bg-sky" },
  c2: { color1: "bg-lilac", color2: "bg-peach" },
  c3: { color1: "bg-midnight", color2: "bg-sky" },
  c4: { color1: "bg-sky", color2: "bg-peach" },
  c5: { color1: "bg-olive", color2: "bg-jade" },
  c6: { color1: "bg-sky", color2: "bg-orange" },
  c7: { color1: "bg-olive", color2: "bg-sky" },
  c8: { color1: "bg-watermelon", color2: "bg-jade" },
  c9: { color1: "bg-olive", color2: "bg-sky" },
  c10: { color1: "bg-watermelon", color2: "bg-jade" },
  d1: { color1: "bg-sky", color2: "bg-lilac" },
  d2: { color1: "bg-peach", color2: "bg-watermelon" },
  d3: { color1: "bg-sky", color2: "bg-watermelon" },
  d4: { color1: "bg-peach", color2: "bg-watermelon" },
  d5: { color1: "bg-jade", color2: "bg-lime" },
  d6: { color1: "bg-orange", color2: "bg-jade" },
  d7: { color1: "bg-sky", color2: "bg-watermelon" },
  d8: { color1: "bg-jade", color2: "bg-lime" },
  d9: { color1: "bg-sky", color2: "bg-watermelon" },
  d10: { color1: "bg-jade", color2: "bg-magenta" },
  e1: { color1: "bg-lilac", color2: "bg-watermelon" },
  e2: { color1: "bg-blush", color2: "bg-olive" },
  e3: { color1: "bg-watermelon", color2: "bg-lime" },
  e4: { color1: "bg-watermelon", color2: "bg-lime" },
  e5: { color1: "bg-lime", color2: "bg-midnight" },
  e6: { color1: "bg-jade", color2: "bg-apricot" },
  e7: { color1: "bg-watermelon", color2: "bg-peach" },
  e8: { color1: "bg-blush", color2: "bg-olive" },
  e9: { color1: "bg-watermelon", color2: "bg-lime" },
  e10: { color1: "bg-jade", color2: "bg-apricot" },
  f1: { color1: "bg-watermelon", color2: "bg-olive" },
  f2: { color1: "bg-olive", color2: "bg-orange" },
  f3: { color1: "bg-jade", color2: "bg-apricot" },
  f4: { color1: "bg-lime", color2: "bg-orange" },
  f5: { color1: "bg-emerald", color2: "bg-orange" },
  f6: { color1: "bg-apricot", color2: "bg-lilac" },
  f7: { color1: "bg-lilac", color2: "bg-apricot" },
  f8: { color1: "bg-sky", color2: "bg-orange" },
  f9: { color1: "bg-midnight", color2: "bg-orange" },
  f10: { color1: "bg-watermelon", color2: "bg-sky" },
};
