type ColorStyle = {
  [name: string]: string;
};

export const colorStyle: ColorStyle = {
  a1: "bg-orange drop-shadow-smLime",
  a2: "bg-magenta drop-shadow-smApricot",
  a3: "bg-lime drop-shadow-smOrange",
  a4: "bg-jade drop-shadow-smApricot",
  a5: "bg-sky drop-shadow-smWatermelon",
  a6: "bg-watermelon drop-shadow-smEmerald",
  a7: "bg-orange drop-shadow-smLime",
  a8: "bg-lilac drop-shadow-smApricot",
  a9: "bg-emerald drop-shadow-smApricot",
  a10: "bg-lime drop-shadow-smLilac",

  b1: "bg-apricot drop-shadow-smJade",
  b2: "bg-watermelon drop-shadow-smLilac",
  b3: "bg-orange drop-shadow-smEmerald",
  b4: "bg-apricot drop-shadow-smSky",
  b5: "bg-watermelon drop-shadow-smOlive",
  b6: "bg-midnight drop-shadow-smSky",
  b7: "bg-lime drop-shadow-smMidnight",
  b8: "bg-apricot drop-shadow-smWatermelon",
  b9: "bg-apricot drop-shadow-smLilac",
  b10: "bg-lilac drop-shadow-smWatermelon",

  c1: "bg-emerald drop-shadow-smSky",
  c2: "bg-lilac drop-shadow-smPeach",
  c3: "bg-midnight drop-shadow-smSky",
  c4: "bg-sky drop-shadow-smPeach",
  c5: "bg-olive drop-shadow-smJade",
  c6: "bg-sky drop-shadow-smOrange",
  c7: "bg-olive drop-shadow-smSky",
  c8: "bg-watermelon drop-shadow-smJade",
  c9: "bg-olive drop-shadow-smSky",
  c10: "bg-watermelon drop-shadow-smJade",

  d1: "bg-sky drop-shadow-smLilac",
  d2: "bg-peach drop-shadow-smWatermelon",
  d3: "bg-sky drop-shadow-smWatermelon",
  d4: "bg-peach drop-shadow-smWatermelon",
  d5: "bg-jade drop-shadow-smLime",
  d6: "bg-orange drop-shadow-smJade",
  d7: "bg-sky drop-shadow-smWatermelon",
  d8: "bg-jade drop-shadow-smLime",
  d9: "bg-sky drop-shadow-smWatermelon",
  d10: "bg-jade drop-shadow-smMagenta",

  e1: "bg-lilac drop-shadow-smWatermelon",
  e2: "bg-blush drop-shadow-smOlive",
  e3: "bg-watermelon drop-shadow-smLime",
  e4: "bg-watermelon drop-shadow-smLime",
  e5: "bg-lime drop-shadow-smMidnight",
  e6: "bg-jade drop-shadow-smApricot",
  e7: "bg-watermelon drop-shadow-smPeach",
  e8: "bg-blush drop-shadow-smOlive",
  e9: "bg-watermelon drop-shadow-smLime",
  e10: "bg-jade drop-shadow-smApricot",

  f1: "bg-watermelon drop-shadow-smOlive",
  f2: "bg-olive drop-shadow-smOrange",
  f3: "bg-jade drop-shadow-smApricot",
  f4: "bg-lime drop-shadow-smOrange",
  f5: "bg-emerald drop-shadow-smOrange",
  f6: "bg-apricot drop-shadow-smLilac",
  f7: "bg-lilac drop-shadow-smApricot",
  f8: "bg-sky drop-shadow-smOrange",
  f9: "bg-midnight drop-shadow-smOrange",
  f10: "bg-watermelon drop-shadow-smSky",
};
