export const skillsList = [
  // need to add language options here
  "Software Development",
  "Nursing",
  "Accounting",
  "Data Analysis",
  "Project Management",
  "Graphic Design",
  "Digital Marketing",
  "Cybersecurity",
  "Public Speaking",
  "Event Planning",
  "Copywriting",
  "Social Media Management",
  "Web Development",
  "Mobile App Development",
  "Artificial Intelligence",
  "Machine Learning",
  "Cloud Computing",
  "Human Resources Management",
  "Sales",
  "Customer Service",
  "Supply Chain Management",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Video Editing",
  "Photography",
  "UX/UI Design",
  "Content Writing",
  "Search Engine Optimization (SEO)",
  "Business Analysis",
  "Investment Banking",
  "Teaching",
  "Legal Research",
  "Tax Preparation",
  "Carpentry",
  "Welding",
  "Graphic Illustration",
  "Translation",
  "Game Development",
  "3D Modeling",
  "Music Production",
  "Bartending",
  "Cooking",
  "Fitness Training",
  "Speech Therapy",
  "Financial Planning",
  "Real Estate Management",
  "Plumbing",
  "Interior Design",
  "Veterinary Care",
  "Robotics Engineering",
];
