export const skillsList = [
  "Software Development",
  "Nursing",
  "Accounting",
  "Data Analysis",
  "Project Management",
  "Graphic Design",
  "Digital Marketing",
  "Cybersecurity",
  "Public Speaking",
  "Event Planning",
  "Copywriting",
  "Social Media Management",
  "Web Development",
  "Mobile App Development",
  "Artificial Intelligence",
  "Machine Learning",
  "Human Resources Management",
  "Sales",
  "Customer Service",
  "Supply Chain Management",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Video Editing",
  "Photography",
  "Content Writing",
  "Search Engine Optimization (SEO)",
  "Business Analysis",
  "Investment Banking",
  "Teaching",
  "Legal Research",
  "Tax Preparation",
  "Carpentry",
  "Welding",
  "Graphic Illustration",
  "Translation",
  "Game Development",
  "3D Modeling",
  "Music Production",
  "Bartending",
  "Cooking",
  "Fitness Training",
  "Speech Therapy",
  "Financial Planning",
  "Real Estate Management",
  "Plumbing",
  "Interior Design",
  "Veterinary Care",
  "Robotics Engineering",
  "Technical Troubleshooting",
  "IT Support",

  // More Specific Skills
  // Software Development and Engineering
  "React.js",
  "Angular",
  "Vue.js",
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "Ruby",
  "Go",
  "PHP",
  "SQL",
  "NoSQL",
  "MongoDB",
  "Cassandra",
  "DevOps",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "CI/CD",
  "AWS",
  "Azure",
  "Google Cloud",
  "Version Control",
  "Git",
  "GitHub",
  "GitLab",
  "Testing Frameworks",
  "Jest",
  "Mocha",
  "Selenium",
  "RESTful APIs",
  "GraphQL",
  "Agile",
  "Scrum",
  "Data Structures and Algorithms",
  "Mobile Development",
  "Swift",
  "Kotlin",
  "Flutter",
  "React Native",
  "Problem-solving",
  "Team collaboration",
  "Code optimization",
  "Debugging",

  // Front-End Engineering
  "Responsive Design",
  "Figma",
  "Adobe XD",
  "Sketch",
  "Browser DevTools",
  "CSS Frameworks",
  "Bootstrap",
  "TailwindCSS",
  "JavaScript Frameworks",
  "React",
  "Next.js",
  "Svelte",
  "Accessibility Standards",
  "WCAG",
  "Cross-Browser Compatibility Testing",
  "Performance Optimization",

  // Healthcare (Nursing, Medical Fields)
  "Patient Care",
  "Patient Assessment",
  "Medical Equipment Operation",
  "Electronic Medical Records",
  "EMR Systems",
  "IV Therapy",
  "CPR",
  "First Aid",
  "Medication Administration",
  "Wound Care",
  "Dressing",
  "Telehealth Technology",
  "Empathy",
  "Active Listening",
  "Stress Management",
  "Multitasking",
  "Patient Advocacy",

  // Creative Fields (Copywriting, Content Creation, Marketing)
  "Ad Copy",
  "Blogging",
  "Instagram",
  "TikTok",
  "LinkedIn",
  "Content Management Systems",
  "WordPress",
  "HubSpot",
  "Canva",
  "Photoshop",
  "Illustrator",
  "Email Marketing",
  "Mailchimp",
  "ActiveCampaign",
  "Analytics Tools",
  "Google Analytics",
  "SEMrush",
  "Paid Advertising",
  "Google Ads",
  "Facebook Ads",
  "Creativity",
  "Storytelling",
  "Audience Analysis",
  "Brand Voice Consistency",

  // Customer Support/Technical Support
  "CRM Tools",
  "Salesforce",
  "Zendesk",
  "HubSpot",
  "Ticketing Systems",
  "Freshdesk",
  "Jira",
  "Problem Resolution",
  "Knowledge Base Maintenance",
  "Remote Assistance Tools",
  "TeamViewer",
  "AnyDesk",
  "Conflict Resolution",
  "Patience",
  "Clear Communication",
  "Time Management",

  // Business and Management
  "Project Management Tools",
  "Asana",
  "Trello",
  "Excel",
  "Tableau",
  "Power BI",
  "Financial Modeling",
  "Forecasting",
  "Enterprise Software",
  "SAP",
  "Oracle",
  "Leadership",
  "Decision Making",
  "Negotiation",
  "Delegation",

  // General Skills
  "Microsoft Office Suite",
  "Word",
  "PowerPoint",
  "Communication",
  "Verbal Communication",
  "Written Communication",
  "Presentation",
  "Research",
  "Analysis",
  "Time Management",
  "Adaptability",
  "Critical Thinking",
  "Networking",
  "Language Proficiency",
  "Multilingualism",
  "Teamwork",
  "Collaboration",

  // Accounting
  "Financial Accounting",
  "Managerial Accounting",
  "Taxation",
  "Auditing",
  "Forensic Accounting",
  "Payroll Management",
  "Cost Accounting",
  "Bookkeeping",
  "QuickBooks",
  "Xero",
  "Sage",
  "Financial Reporting",
  "Balance Sheets",
  "Cash Flow Management",
  "Budgets and Forecasting",
  "Internal Controls",
  "GAAP",
  "IFRS",
  "Financial Analysis",
  "Variance Analysis",
  "Accounting Software",
  "ERP Systems",
  "Reconciliation",
  "Compliance",
  "Attention to Detail",
  "Analytical Skills",
  "Problem Solving",

  // Mechanics
  "Troubleshooting",
  "Preventative Maintenance",
  "Hydraulic Systems",
  "Pneumatic Systems",
  "Milling",
  "Lathe Operation",
  "Auto Repair",
  "Engine Diagnostics",
  "Powertrain Systems",
  "Brake Systems",
  "Electrical Systems",
  "Diagnostics Tools",
  "Blueprint Reading",
  "CAD Software",
  "Machine Design",
  "Pump and Motor Maintenance",
  "Safety Procedures",
  "Torque Wrenching",
  "Materials Science",
  "Vibration Analysis",
  "Troubleshooting and Repair",
  "Mechanical Assembly",

  // Consulting
  "Strategic Planning",
  "Business Process Improvement",
  "Market Research",
  "Change Management",
  "Operational Efficiency",
  "Risk Management",
  "Financial Consulting",
  "Stakeholder Management",
  "SWOT Analysis",
  "Management Consulting",
  "Business Analytics",
  "Cost-Benefit Analysis",
  "Organizational Development",
  "Financial Forecasting",
  "Mergers and Acquisitions",
  "Feasibility Studies",
  "Leadership Coaching",
  "Corporate Governance",
  "Business Transformation",
  "Client Relations",
  "Negotiation Skills",

  // Banking
  "Retail Banking",
  "Corporate Banking",
  "Risk Assessment",
  "Lending",
  "Underwriting",
  "Loan Processing",
  "Credit Analysis",
  "Mortgage Lending",
  "Banking Regulations",
  "AML (Anti-Money Laundering)",
  "KYC (Know Your Customer)",
  "Derivatives",
  "Capital Markets",
  "Private Equity",
  "Wealth Management",
  "Asset Management",
  "Securities Trading",
  "Tax-Exempt Financing",
  "Customer Relationship Management",
  "Cash Management",
  "Compliance and Auditing",

  // Engineering (General)
  "Mechanical Design",
  "Electrical Design",
  "Construction Management",
  "Project Planning",
  "Surveying",
  "AutoCAD",
  "Structural Analysis",
  "Geotechnical Engineering",
  "Project Estimation",
  "Quality Control",
  "Safety Management",
  "Infrastructure Design",
  "Site Management",
  "Cost Control",
  "Engineering Analysis",

  // Legal (Law and Compliance)
  "Contract Law",
  "Corporate Law",
  "Intellectual Property",
  "Litigation",
  "Mediation",
  "Employment Law",
  "Family Law",
  "Tax Law",
  "Legal Drafting",
  "Legal Compliance",
  "Regulatory Affairs",
  "Due Diligence",
  "Dispute Resolution",
  "Legal Writing",
  "Arbitration",
  "Court Appearances",

  // Education
  "Lesson Planning",
  "Classroom Management",
  "Educational Technology",
  "Curriculum Design",
  "Instructional Design",
  "Student Assessment",
  "Differentiated Instruction",
  "Behavior Management",
  "Special Education",
  "E-Learning Development",
  "Tutoring",
  "Teacher Certification",
  "Student Engagement",
  "Team Collaboration",
  "Peer Mentoring",
  "Educational Administration",

  // Sales and Marketing
  "Sales Strategy",
  "B2B Sales",
  "B2C Sales",
  "Lead Generation",
  "Market Research",
  "Customer Acquisition",
  "Cold Calling",
  "Closing Sales",
  "Sales Forecasting",
  "Digital Marketing",
  "PPC",
  "Content Marketing",
  "Social Media Marketing",
  "Brand Development",
  "Public Relations",
  "Market Segmentation",
  "Sales Presentations",
  "Networking",
  "Relationship Building",
  "Event Planning",
  "Product Launches",

  // Human Resources
  "Recruitment",
  "Talent Acquisition",
  "Employee Onboarding",
  "Training and Development",
  "Performance Management",
  "Employee Relations",
  "Compensation and Benefits",
  "Payroll Administration",
  "HRIS Systems",
  "Labor Laws",
  "Workplace Diversity",
  "Employee Engagement",
  "Succession Planning",
  "HR Policies",
  "Legal Compliance",
  "Health and Safety",
  "Workforce Planning",

  // IT and Cybersecurity
  "Network Administration",
  "Server Management",
  "Ethical Hacking",
  "Firewall Management",
  "Penetration Testing",
  "Vulnerability Assessment",
  "Cloud Security",
  "Incident Response",
  "Data Encryption",
  "Security Information and Event Management (SIEM)",
  "Intrusion Detection Systems",
  "Identity and Access Management",
  "Network Security",
  "Malware Analysis",
  "Security Audits",
  "Disaster Recovery Planning",
  "Cryptography",

  // Logistics and Supply Chain
  "Inventory Management",
  "Warehouse Management",
  "Supply Chain Optimization",
  "Logistics Planning",
  "Freight Management",
  "Transportation Management",
  "Procurement",
  "Vendor Management",
  "Demand Forecasting",
  "Supply Chain Software",
  "Lean Manufacturing",
  "Material Handling",
  "Shipping and Receiving",
  "Route Planning",
  "Cost Control",
  "Contract Negotiation",
  "Risk Management",
];
