import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navBar";
import Footer from "@/components/footer";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Straightforward Job Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative overflow-x-hidden">
        <Theme
          panelBackground="solid"
          radius="large"
          className="flex min-h-screen w-full flex-col bg-cream"
        >
          <NavBar />
          <div className="Main flex flex-1 flex-col">{children}</div>
          <Footer />
        </Theme>
      </body>
    </html>
  );
}
